"""
Incremental refresh data generator.
Run on schedule to drop new sales files into the landing zone.

Franchise A: ONE weekly file  (7 days from REFRESH_START_DATE)
Franchise B: ONE file per day (7 daily files from REFRESH_START_DATE)

Reads master data generated by SeedDataGenerator (product_master, customer_master,
barcode_sku_mapping) so sales reference real SKUs, barcodes, and loyalty IDs.
"""
import pandas as pd
import numpy as np
import uuid
import random
from faker import Faker
import os
import time
from datetime import datetime, timedelta
from concurrent.futures import ProcessPoolExecutor, as_completed
from multiprocessing import cpu_count

fake_en = Faker('en_IN')
fake_hi = Faker('hi_IN')
HINDI_PCT = 0.15               # ~15% of names/labels will be in Hindi

HINDI_STORE_NAMES = [
    "श्री वस्त्र भंडार",
    "नया फैशन हाउस",
    "राज वस्त्रालय",
]

# ──────────────────── CONSTANTS ────────────────────
ROWS_FRANCHISE_A = 500_000     # Base rows for the weekly file
ROWS_FRANCHISE_B = 150_000     # Base rows per daily file
CHUNK_SIZE = 500_000           # Rows per chunk (controls memory)
MAX_WORKERS = max(1, cpu_count() - 1)
STORE_COUNT_A = 10
HUB_COUNT_B = 500
ROWS_VARIANCE_PCT = 30         # ±% variance in rows
LOYALTY_BLANK_MAX_PCT = 0.21   # Max fraction of customers without loyalty ID
LOYALTY_VARIANCE_PCT = 20      # % below max — actual rate per chunk randomised
ERROR_PCT = 0.005              # ~0.5 % rows get a data-quality error

# India geo bounds
INDIA_LAT_MIN, INDIA_LAT_MAX = 8.0, 35.0
INDIA_LON_MIN, INDIA_LON_MAX = 68.0, 97.0

INDIA_CITIES = [
    ("Bengaluru", "KA"), ("Mysuru", "KA"),
    ("Mumbai", "MH"), ("Pune", "MH"), ("Nagpur", "MH"),
    ("Delhi", "DL"), ("Noida", "UP"), ("Lucknow", "UP"),
    ("Chennai", "TN"), ("Coimbatore", "TN"),
    ("Kolkata", "WB"), ("Hyderabad", "TS"),
    ("Ahmedabad", "GJ"), ("Jaipur", "RJ"),
    ("Kochi", "KL"), ("Bhopal", "MP"),
    ("Patna", "BR"), ("Chandigarh", "CH"),
    ("Guwahati", "AS"), ("Indore", "MP"),
]

# Refresh config — set per run
REFRESH_START_DATE = datetime(2026, 4, 1)
FRANCHISE_A_DAYS = 7           # Weekly cadence (always 7)
FRANCHISE_B_DAYS = 1           # Daily cadence  (always 1)

OUTPUT_DIR_MASTER = os.path.join("storage", "landing_zone", "master_company")
OUTPUT_DIR_A = os.path.join("storage", "landing_zone", "franchise_a")
OUTPUT_DIR_B = os.path.join("storage", "landing_zone", "franchise_b")
# ───────────────────────────────────────────────────

_HEX = np.array(list('0123456789abcdef'))


# ── LOAD MASTER DATA FROM SEED ───────────────────
def _load_masters():
    """Load master data generated by SeedDataGenerator."""
    product_path = os.path.join(OUTPUT_DIR_MASTER, "product_master.csv")
    customer_path = os.path.join(OUTPUT_DIR_MASTER, "customer_master.csv")
    mapping_path = os.path.join(OUTPUT_DIR_B, "barcode_sku_mapping.psv")

    for p in [product_path, customer_path, mapping_path]:
        if not os.path.exists(p):
            raise FileNotFoundError(
                f"Master file not found: {p}\n"
                "Run SeedDataGenerator.py first to create master data."
            )

    product_df = pd.read_csv(product_path, encoding='utf-8-sig')
    customer_df = pd.read_csv(customer_path, encoding='utf-8-sig')
    mapping_df = pd.read_csv(mapping_path, sep="|", encoding='utf-8-sig')

    return (
        product_df['sku_code'].values,
        customer_df['customer_id'].values,
        mapping_df['item_barcode'].values,
    )


# ── HELPERS ──────────────────────────────────────
def _rand_timestamps(n, start, end):
    delta_s = int((end - start).total_seconds())
    offsets = np.random.randint(0, max(delta_s, 1), size=n)
    epoch = np.datetime64(start, 's')
    return epoch + offsets.astype('timedelta64[s]')


def _fast_hex_ids(n, length=16):
    raw = np.random.choice(_HEX, size=(n, length))
    return np.array([''.join(row) for row in raw])


def _fast_prefixed_ids(prefix, n, low, high):
    nums = np.random.randint(low, high, size=n)
    return np.char.add(prefix, nums.astype(str))


def _randomize_rows(base, variance_pct):
    lo = base * (1 - variance_pct / 100)
    hi = base * (1 + variance_pct / 100)
    return int(random.uniform(lo, hi))


def _inject_errors_a(df):
    n = len(df)
    err_count = max(1, int(n * ERROR_PCT))
    idx = np.random.choice(n, size=err_count, replace=False)
    third = err_count // 3
    df.iloc[idx[:third], df.columns.get_loc('quantity')] = -500
    df.iloc[idx[:third], df.columns.get_loc('transaction_type')] = 'RETURN'
    df.iloc[idx[third:2*third], df.columns.get_loc('unit_price')] = np.nan
    df.iloc[idx[2*third:], df.columns.get_loc('transaction_timestamp')] = np.datetime64('2030-01-01')
    return df


def _inject_errors_b(df):
    n = len(df)
    err_count = max(1, int(n * ERROR_PCT))
    idx = np.random.choice(n, size=err_count, replace=False)
    third = err_count // 3
    df.iloc[idx[:third], df.columns.get_loc('mrp_price')] = 0.00
    s2 = idx[third:2*third]
    if len(s2):
        df.iloc[s2, df.columns.get_loc('order_uuid')] = df.iloc[s2[0], df.columns.get_loc('order_uuid')]
    df.iloc[idx[2*third:], df.columns.get_loc('discount_applied')] = -1000.00
    return df


# ── MASTER REFRESH ───────────────────────────────
def refresh_masters():
    os.makedirs(OUTPUT_DIR_A, exist_ok=True)
    os.makedirs(OUTPUT_DIR_B, exist_ok=True)

    # Franchise A: store master — one new store added
    _store_codes_list = [f"FA-{i:03d}" for i in range(1, STORE_COUNT_A + 2)]
    pairs = [random.choice(INDIA_CITIES) for _ in _store_codes_list]
    pd.DataFrame({
        'store_code': _store_codes_list,
        'store_name': [
            random.choice(HINDI_STORE_NAMES) if random.random() < HINDI_PCT else fake_en.company()
            for _ in _store_codes_list
        ],
        'city': [c for c, _ in pairs],
        'state': [s for _, s in pairs]
    }).to_csv(os.path.join(OUTPUT_DIR_A, "storemaster_monthly_refresh.csv"), index=False, encoding='utf-8-sig')

    # Franchise B: hub master — two new hubs added
    _hub_ids_list = [str(uuid.uuid4())[:8] for _ in range(HUB_COUNT_B + 2)]
    cnt = len(_hub_ids_list)
    pd.DataFrame({
        'hub_id': _hub_ids_list,
        'hub_name': [f"Hub-{random.choice(INDIA_CITIES)[0]}" for _ in _hub_ids_list],
        'pincode': np.random.randint(110000, 856000, size=cnt).astype(str),
        'latitude': np.round(np.random.uniform(INDIA_LAT_MIN, INDIA_LAT_MAX, cnt), 6),
        'longitude': np.round(np.random.uniform(INDIA_LON_MIN, INDIA_LON_MAX, cnt), 6)
    }).to_csv(os.path.join(OUTPUT_DIR_B, "hubmaster_weekly_refresh.psv"), index=False, sep="|", encoding='utf-8-sig')


# ── CHUNK GENERATORS ─────────────────────────────
def _gen_chunk_a(n, start, end, sku_codes, loyalty_ids):
    blank_rate = random.uniform(
        LOYALTY_BLANK_MAX_PCT * (1 - LOYALTY_VARIANCE_PCT / 100),
        LOYALTY_BLANK_MAX_PCT
    )
    loyalty_mask = np.random.random(n) > blank_rate
    cust_ids = np.where(loyalty_mask, np.random.choice(loyalty_ids, size=n), '')

    store_codes = np.array([f"FA-{i:03d}" for i in range(1, STORE_COUNT_A + 1)])
    df = pd.DataFrame({
        'invoice_number': _fast_prefixed_ids("INV-", n, 10000, 100000),
        'store_code': np.random.choice(store_codes, size=n),
        'transaction_timestamp': _rand_timestamps(n, start, end),
        'sku_code': np.random.choice(sku_codes, size=n),
        'quantity': np.random.randint(1, 6, size=n),
        'unit_price': np.round(np.random.uniform(299, 9999, size=n), 2),
        'transaction_type': np.full(n, 'SALE'),
        'customer_id': cust_ids
    })
    return _inject_errors_a(df)


def _gen_chunk_b(n, start, end, fb_barcodes, hub_ids):
    df = pd.DataFrame({
        'order_uuid': _fast_hex_ids(n),
        'hub_id': np.random.choice(hub_ids, size=n),
        'item_barcode': np.random.choice(fb_barcodes, size=n),
        'units_sold': np.random.randint(1, 4, size=n),
        'mrp_price': np.round(np.random.uniform(299, 9999, size=n), 2),
        'discount_applied': np.round(np.random.uniform(0, 500, size=n), 2),
        'delivery_timestamp': _rand_timestamps(n, start, end),
        'status': np.random.choice(
            np.array(["DELIVERED", "RETURNED", "CANCELLED"]),
            size=n, p=[0.85, 0.10, 0.05])
    })
    return _inject_errors_b(df)


# ── FRANCHISE A: ONE weekly file ─────────────────
def refresh_sales_a(sku_codes, loyalty_ids):
    week_start = REFRESH_START_DATE
    week_end = week_start + timedelta(days=FRANCHISE_A_DAYS - 1, hours=23, minutes=59, seconds=59)
    actual_rows = _randomize_rows(ROWS_FRANCHISE_A, ROWS_VARIANCE_PCT)

    fname = os.path.join(OUTPUT_DIR_A, f"sales_weekly_{week_start:%Y_%m_%d}.csv")
    os.makedirs(OUTPUT_DIR_A, exist_ok=True)

    t0 = time.time()
    first = True
    written = 0
    while written < actual_rows:
        n = min(CHUNK_SIZE, actual_rows - written)
        _gen_chunk_a(n, week_start, week_end, sku_codes, loyalty_ids).to_csv(
            fname, index=False, mode='a', header=first, encoding='utf-8-sig' if first else 'utf-8')
        first = False
        written += n
    print(f"  {fname}  ({written:,} rows, {week_start:%Y-%m-%d} to {week_end:%Y-%m-%d}, {time.time()-t0:.1f}s)")


# ── FRANCHISE B: ONE file per day (parallel) ─────
def _write_daily_b(args):
    fname, total_rows, day_start, day_end, fb_barcodes, hub_ids = args
    os.makedirs(os.path.dirname(fname), exist_ok=True)
    t0 = time.time()
    first = True
    written = 0
    while written < total_rows:
        n = min(CHUNK_SIZE, total_rows - written)
        _gen_chunk_b(n, day_start, day_end, fb_barcodes, hub_ids).to_csv(
            fname, index=False, sep="|", mode='a', header=first, encoding='utf-8-sig' if first else 'utf-8')
        first = False
        written += n
    return f"  {fname}  ({written:,} rows, {day_start:%Y-%m-%d}, {time.time()-t0:.1f}s)"


def refresh_sales_b(fb_barcodes):
    os.makedirs(OUTPUT_DIR_B, exist_ok=True)
    hub_ids = np.array([str(uuid.uuid4())[:8] for _ in range(HUB_COUNT_B)])

    tasks = []
    for d in range(FRANCHISE_A_DAYS):
        day = REFRESH_START_DATE + timedelta(days=d)
        day_end = day.replace(hour=23, minute=59, second=59)
        actual_rows = _randomize_rows(ROWS_FRANCHISE_B, ROWS_VARIANCE_PCT)
        fname = os.path.join(OUTPUT_DIR_B, f"sales_daily_{day:%Y_%m_%d}.psv")
        tasks.append((fname, actual_rows, day, day_end, fb_barcodes, hub_ids))

    with ProcessPoolExecutor(max_workers=MAX_WORKERS) as pool:
        futures = {pool.submit(_write_daily_b, t): t for t in tasks}
        for f in as_completed(futures):
            print(f.result())


# ── RUN ──────────────────────────────────────────
if __name__ == "__main__":
    t_start = time.time()
    week_end = REFRESH_START_DATE + timedelta(days=FRANCHISE_A_DAYS - 1)
    print(f"=== REFRESH: {REFRESH_START_DATE:%Y-%m-%d} to {week_end:%Y-%m-%d} ===")

    print("\n--- Loading Master Data (from seed) ---")
    sku_codes, loyalty_ids, fb_barcodes = _load_masters()
    print(f"  {len(sku_codes):,} SKUs, {len(loyalty_ids):,} loyalty customers, {len(fb_barcodes):,} barcodes")

    print("\n--- Updating Franchise Masters ---")
    refresh_masters()

    print(f"\n--- Franchise A: 1 weekly file ({ROWS_FRANCHISE_A:,} base rows ±{ROWS_VARIANCE_PCT}%) ---")
    refresh_sales_a(sku_codes, loyalty_ids)

    print(f"\n--- Franchise B: {FRANCHISE_A_DAYS} daily files ({ROWS_FRANCHISE_B:,} base rows/day ±{ROWS_VARIANCE_PCT}%) ---")
    refresh_sales_b(fb_barcodes)

    print(f"\n=== REFRESH complete in {time.time()-t_start:.1f}s ===")
